import { Injectable, Logger } from "@nestjs/common";
import { HasuraService } from "../hasura/hasura.service";
import { PostgresService } from "../postgres/postgres.service";

// Individual sign-up (match_options.individual_registration_enabled):
// ELO-balances everyone eligible in tournament_individual_signups into
// fresh, ad-hoc tournament_teams (team_id left NULL, same as a brand-new
// tournament-only team created via the normal join form). Extracted out of
// TournamentsController so both the organizer-facing generateTournamentTeams
// action and ProcessTournamentAttendance (the automatic scheduler) call the
// exact same logic -- a click and a timer, not two implementations.
@Injectable()
export class TournamentTeamGenerationService {
  constructor(
    private readonly logger: Logger,
    private readonly hasura: HasuraService,
    private readonly postgres: PostgresService,
  ) {}

  // Callers are responsible for their own authorization/status checks
  // before calling this; it does not re-check is_organizer or tournament
  // status itself.
  //
  // Idempotent: if tournament_teams already exist for this tournament
  // (generated by an earlier manual click or an earlier scheduler tick),
  // this is a clean no-op ({teamsCreated: 0, waitlisted: 0}) rather than
  // attempting a second round of Team 1/Team 2/... inserts that would
  // collide with tournament_teams_tournament_id_name_key.
  //
  // Selection is two separate steps, deliberately in this order:
  //  1. WHO participates: every eligible signup (Registered, or Waitlisted
  //     with checked_in_at set -- a checked-in waitlisted player can still
  //     earn a spot), sorted by ORIGINAL registration time (created_at)
  //     ascending, capped at min(tournament max_teams, floor(eligible /
  //     teamSize)) full teams' worth. Registration priority decides this,
  //     never ELO -- an earlier low-ELO signup is never bumped by a later
  //     high-ELO one.
  //  2. WHICH TEAM: only the selected pool from step 1 is shuffled (for
  //     ELO-tie randomness), sorted by ELO descending, then snake-drafted
  //     across the generated teams -- unchanged from the original
  //     ELO-only implementation, just now applied to a priority-selected
  //     subset instead of everyone Registered.
  public async generateTournamentTeamsForTournament(
    tournamentId: string,
    teamSize: number,
  ): Promise<{ teamsCreated: number; waitlisted: number }> {
    const existingTeams = await this.postgres.query<Array<{ count: string }>>(
      `SELECT COUNT(*)::int AS count FROM public.tournament_teams WHERE tournament_id = $1`,
      [tournamentId],
    );
    if (Number(existingTeams[0]?.count ?? 0) > 0) {
      return { teamsCreated: 0, waitlisted: 0 };
    }

    const { tournament_individual_signups: signups } = await this.hasura.query({
      tournament_individual_signups: {
        __args: {
          where: {
            tournament_id: { _eq: tournamentId },
            _or: [
              { status: { _eq: "Registered" } },
              {
                status: { _eq: "Waitlisted" },
                checked_in_at: { _is_null: false },
              },
            ],
          },
        },
        id: true,
        player_steam_id: true,
        created_at: true,
        player: {
          name: true,
          elo: true,
        },
      },
    });

    if (!signups?.length) {
      throw Error("no eligible individually-registered players to generate teams from");
    }

    const maxTeamsRows = await this.postgres.query<Array<{ max_teams: number }>>(
      `SELECT max_teams FROM public.tournament_stages WHERE tournament_id = $1 AND "order" = 1 LIMIT 1`,
      [tournamentId],
    );
    const maxTeams = maxTeamsRows[0]?.max_teams ?? null;

    const byPriority = [...signups].sort(
      (a, b) =>
        new Date(a.created_at as string).getTime() -
        new Date(b.created_at as string).getTime(),
    );

    const teamCountByHeadcount = Math.floor(byPriority.length / teamSize);
    const teamCount =
      maxTeams != null ? Math.min(maxTeams, teamCountByHeadcount) : teamCountByHeadcount;
    if (teamCount < 1) {
      throw Error(
        `not enough eligible players (${byPriority.length}) for a single ${teamSize}-player team`,
      );
    }

    const assignedCount = teamCount * teamSize;
    const waitlisted = byPriority.slice(assignedCount);
    const selected = byPriority.slice(0, assignedCount);

    // wingman = 2v2, everything else (competitive 5v5, etc.) uses the
    // competitive ladder -- there's no third team-size bracket today.
    const eloKey = teamSize === 2 ? "wingman" : "competitive";

    const shuffled = TournamentTeamGenerationService.shuffle(selected);
    const ranked = shuffled
      .map((signup) => ({
        signupId: signup.id as string,
        steamId: String(signup.player_steam_id),
        name: (signup.player?.name as string) ?? null,
        elo: Number((signup.player?.elo as Record<string, number>)?.[eloKey] ?? 5000),
      }))
      .sort((a, b) => b.elo - a.elo);

    // Snake draft across teamCount teams.
    const teams: Array<typeof ranked> = Array.from(
      { length: teamCount },
      (): typeof ranked => [],
    );
    let round = 0;
    let index = 0;
    while (index < ranked.length) {
      const order =
        round % 2 === 0
          ? Array.from({ length: teamCount }, (_, i) => i)
          : Array.from({ length: teamCount }, (_, i) => teamCount - 1 - i);
      for (const teamIndex of order) {
        if (index >= ranked.length) break;
        teams[teamIndex].push(ranked[index]);
        index++;
      }
      round++;
    }

    await this.postgres.transaction(async (client) => {
      // tbi_tournament_team_roster (hasura/triggers/tournament_team_roster.sql)
      // reads current_setting('hasura.user') to decide whether a roster
      // insert is admin/organizer-driven (allowed straight through) or a
      // regular player join (redirected into a tournament_team_invites
      // row instead). That GUC only exists because Hasura's GraphQL engine
      // sets it per-request -- this raw connection never gets it set,
      // which the trigger treats as an unrecognized-setting error rather
      // than "missing". Fake it for this transaction only: these rosters
      // are entirely organizer- or scheduler-triggered (never a direct
      // player action), so "administrator" here is accurate, not a
      // privilege escalation.
      await client.query(
        `SELECT set_config('hasura.user', '{"x-hasura-role":"administrator"}', true)`,
      );

      // Belt-and-suspenders idempotency: if a concurrent call (manual
      // click racing the scheduler, or two scheduler ticks) already
      // created teams for this tournament since the check above, bail out
      // here instead of colliding on tournament_teams_tournament_id_name_key.
      const raceCheck = await client.query<{ count: string }>(
        `SELECT COUNT(*)::int AS count FROM public.tournament_teams WHERE tournament_id = $1`,
        [tournamentId],
      );
      if (Number(raceCheck.rows[0]?.count ?? 0) > 0) {
        return;
      }

      for (const [teamIndex, roster] of teams.entries()) {
        // Highest-ELO player on the generated roster stands in as
        // owner/captain -- there's no "team owner" concept for a pool of
        // strangers auto-assigned together, this just satisfies
        // tournament_teams.owner_steam_id NOT NULL with a defensible pick.
        const captain = roster[0];
        const teamRow = await client.query<{ id: string }>(
          `INSERT INTO public.tournament_teams
             (tournament_id, name, owner_steam_id, captain_steam_id, team_id)
           VALUES ($1, $2, $3, $3, NULL)
           RETURNING id`,
          [
            tournamentId,
            `Team ${teamIndex + 1}`,
            captain.steamId,
          ],
        );
        const tournamentTeamId = teamRow.rows[0].id;

        for (const player of roster) {
          await client.query(
            `INSERT INTO public.tournament_team_roster
               (tournament_team_id, player_steam_id, tournament_id)
             VALUES ($1, $2, $3)`,
            [tournamentTeamId, player.steamId, tournamentId],
          );
          await client.query(
            `UPDATE public.tournament_individual_signups
             SET status = 'Assigned', tournament_team_id = $1
             WHERE id = $2`,
            [tournamentTeamId, player.signupId],
          );
        }
      }

      if (waitlisted.length) {
        await client.query(
          `UPDATE public.tournament_individual_signups
           SET status = 'Waitlisted'
           WHERE id = ANY($1::uuid[])`,
          [waitlisted.map((player) => player.id)],
        );
      }

      // tbu_tournaments (hasura/triggers/tournaments.sql) rebuilds the
      // whole bracket (update_tournament_stages), seeds every eligible
      // team (assign_seeds_to_teams), then resolves those seeds into
      // actual team_1/team_2 match lineups (seed_stage) -- but only on
      // the Setup/RegistrationOpen -> Live/RegistrationClosed
      // transition, which already happened before any of these teams
      // existed (they're created here, after registration closed).
      // Without re-running all three, the bracket stays built for 0
      // teams, every team sits at seed = NULL, and even once seeded the
      // bracket UI shows bare seed numbers (#1, #2, ...) instead of
      // team names since nothing ever resolved seed -> team into the
      // actual matches.
      await client.query(`SELECT update_tournament_stages($1)`, [
        tournamentId,
      ]);
      await client.query(
        `SELECT assign_seeds_to_teams(t) FROM public.tournaments t WHERE t.id = $1`,
        [tournamentId],
      );
      const firstStage = await client.query<{ id: string }>(
        `SELECT id FROM public.tournament_stages WHERE tournament_id = $1 AND "order" = 1 LIMIT 1`,
        [tournamentId],
      );
      if (firstStage.rows[0]) {
        await client.query(`SELECT seed_stage($1)`, [firstStage.rows[0].id]);
      }
    });

    this.logger.log(
      `[${tournamentId}] generated ${teamCount} team(s) (${assignedCount} players) from individual sign-ups by registration priority, ${waitlisted.length} left waitlisted`,
    );

    return {
      teamsCreated: teamCount,
      waitlisted: waitlisted.length,
    };
  }

  private static shuffle<T>(items: Array<T>): Array<T> {
    const result = [...items];
    for (let index = result.length - 1; index > 0; index--) {
      const swap = Math.floor(Math.random() * (index + 1));
      const temp = result[index];
      result[index] = result[swap];
      result[swap] = temp;
    }
    return result;
  }
}
