INSERT INTO e_notification_types ("value", "description") VALUES
    ('GameUpdate', 'GameUpdate'),
    ('MatchSupport', 'MatchSupport'),
    ('GameNodeStatus', 'GameNodeStatus'),
    ('NameChangeRequest', 'NameChangeRequest'),
    ('NameChangeApproved', 'Your name change request was approved'),
    ('NameChangeDenied', 'Your name change request was denied'),
    ('DedicatedServerStatus', 'DedicatedServerStatus'),
    ('DedicatedServerRconStatus', 'DedicatedServerRconStatus'),
    ('MatchStatusChange', 'Match Status Change Notification'),
    ('StorageScan', 'Storage Scan'),
    ('PlayerSanctioned', 'A player you recently played with received a sanction'),
    ('ScrimRequestReceived', 'A team requested to scrim yours'),
    ('ScrimRequestCountered', 'A team proposed a different scrim time'),
    ('ScrimRequestAccepted', 'Your scrim request was accepted'),
    ('ScrimRequestDeclined', 'Your scrim request was declined'),
    ('ScrimRequestExpired', 'A scrim request expired without a response'),
    ('ScrimMatchScheduled', 'A scrim match has been scheduled'),
    ('ScrimMatchCanceled', 'A scheduled scrim match was canceled'),
    ('ScrimTimeChanged', 'A scheduled scrim time changed'),
    ('ScrimAlertMatch', 'A team matching your scrim alert is available'),
    ('FormTeamSuggestion', 'You frequently play with these players'),
    ('EloRecompute', 'Player ELO recompute finished'),
    ('PlayerReindex', 'Player search reindex finished'),
    ('LeagueProposalReceived', 'A league opponent proposed a match time'),
    ('LeagueProposalAccepted', 'Your league match time proposal was accepted'),
    ('LeagueProposalDeclined', 'Your league match time proposal was declined'),
    ('LeagueMatchUnscheduled', 'A league matchup is unscheduled and will default soon'),
    ('LeagueRegistrationDecision', 'Your league registration was reviewed'),
    ('LeagueRosterUndersized', 'Your league team no longer meets the minimum roster size')
ON CONFLICT("value") DO UPDATE
    SET "description" = EXCLUDED."description";
